### ISSUE TITLE
[Collection] Groups have to be direct children of the collection

### ISSUE THREAD

**Issue by Tom32i** [Elao/form.js#7]
For the collection items initialization process to work, the groups have to be direct DOM children of the collection element.

This should _at least_ be indicated in documentation.

**Comment by yoh** [comment]
I think problem come from here : 
https://github.com/Elao/form.js/blob/master/src/collection/Collection.js#L225

**Comment by benji07** [comment]
Spring cleaning, If this issue is still relevant, please reopen-it.
